# WHAT TO DO:


# Correct AIC and LRT for survey data using stats:::extractAIC
# save summary to a file, file=NULL default

# refit vglm with vglm starting values
# . option in gotm() to use only vglm starting values (no fitting) - DONE
# . remove gamma.est.method and lambda.est.method - DONE
# . remove offset - DONE
# remove unimporant fields in output model oject
# . use match.arg - DONE
# . analitical gradient - DONE
# repair unravel
# . omit calcualtion of hessian and gradient, coorect spelling - DONE
# more complicated survey designs
# add subset
# different kinds of plot , by enter, or to file(s), or in 2x2 format

