# WHAT TO DO:

# refit vglm with vglm starting values
# . option in gotm() to use only vglm starting values (no fitting) - DONE
# . remove gamma.est.method and lambda.est.method - DONE
# . remove offset - DONE
# remove unimporant fields in output model oject
# . use match.arg - DONE
# analitical gradient
# repair unravel
# . omit calcualtion of hessian and gradient, coorect spelling - DONE
# more complicated survey designs
# add subset
# "vglm" fit by default with warning message, or "full" by defaul with message that "vglm" is faster, but may be not precise. add "fasterfull" for control maxiter=1, check in reiter to no to repeat 
# predict "class" as "alias" to response

