# WHAT TO DO:

# refit vglm with vglm starting values
# . option in gotm() to use only vglm starting values (no fitting) - DONE
# . remove gamma.est.method and lambda.est.method - DONE
# . remove offset - DONE
# remove unimporant fields in output model oject
# . use match.arg - DONE
# analitical gradient
# repair unravel
# more complicated survey designs
# OPCJA effect signle gamma modelowany przez vglm tak, ze single gamma nie idzie do FALSE~ tylko do glownego
#   potem jest to odpowiednio przeliczane

# sprawdzic czy nazwy zgadzaja sie z parametrami - PARTIALY
# omit calcualtion of hessian and gradient, coorect spelling