// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// dstdnorm
Eigen::VectorXd dstdnorm(const Eigen::VectorXd v);
RcppExport SEXP _gotm_dstdnorm(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(dstdnorm(v));
    return rcpp_result_gen;
END_RCPP
}
// pstdlogit
Eigen::VectorXd pstdlogit(const Eigen::VectorXd v);
RcppExport SEXP _gotm_pstdlogit(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(pstdlogit(v));
    return rcpp_result_gen;
END_RCPP
}
// dstdlogit
Eigen::VectorXd dstdlogit(const Eigen::VectorXd v);
RcppExport SEXP _gotm_dstdlogit(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(dstdlogit(v));
    return rcpp_result_gen;
END_RCPP
}
// colpath
Eigen::VectorXd colpath(const Eigen::MatrixXd m, const Eigen::VectorXi v, const int offset);
RcppExport SEXP _gotm_colpath(SEXP mSEXP, SEXP vSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(colpath(m, v, offset));
    return rcpp_result_gen;
END_RCPP
}
// extract_elements
Eigen::VectorXd extract_elements(const Eigen::VectorXi x, const int offset, const Eigen::VectorXd v);
RcppExport SEXP _gotm_extract_elements(SEXP xSEXP, SEXP offsetSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_elements(x, offset, v));
    return rcpp_result_gen;
END_RCPP
}
// vglm2gotm_jurges_exp
SEXP vglm2gotm_jurges_exp(const Eigen::VectorXd reg_params, const Eigen::VectorXd thresh_lambda, const Eigen::VectorXd thresh_gamma);
RcppExport SEXP _gotm_vglm2gotm_jurges_exp(SEXP reg_paramsSEXP, SEXP thresh_lambdaSEXP, SEXP thresh_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type reg_params(reg_paramsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type thresh_lambda(thresh_lambdaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type thresh_gamma(thresh_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(vglm2gotm_jurges_exp(reg_params, thresh_lambda, thresh_gamma));
    return rcpp_result_gen;
END_RCPP
}
// ind_reg_thresh
Eigen::MatrixXd ind_reg_thresh(const Eigen::MatrixXd thresh_mm, const Eigen::VectorXd thresh_lambda, const Eigen::VectorXd thresh_gamma);
RcppExport SEXP _gotm_ind_reg_thresh(SEXP thresh_mmSEXP, SEXP thresh_lambdaSEXP, SEXP thresh_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_mm(thresh_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type thresh_lambda(thresh_lambdaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type thresh_gamma(thresh_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(ind_reg_thresh(thresh_mm, thresh_lambda, thresh_gamma));
    return rcpp_result_gen;
END_RCPP
}
// getThresholds
Eigen::MatrixXd getThresholds(const Eigen::MatrixXd thresh_mm, const Eigen::VectorXd thresh_lambda, const Eigen::VectorXd thresh_gamma, const int thresh_no_cov);
RcppExport SEXP _gotm_getThresholds(SEXP thresh_mmSEXP, SEXP thresh_lambdaSEXP, SEXP thresh_gammaSEXP, SEXP thresh_no_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_mm(thresh_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type thresh_lambda(thresh_lambdaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type thresh_gamma(thresh_gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type thresh_no_cov(thresh_no_covSEXP);
    rcpp_result_gen = Rcpp::wrap(getThresholds(thresh_mm, thresh_lambda, thresh_gamma, thresh_no_cov));
    return rcpp_result_gen;
END_RCPP
}
// LLFunc
double LLFunc(const Eigen::Map<Eigen::VectorXd> parameters, const Eigen::VectorXi yi, const Eigen::MatrixXd reg_mm, const Eigen::MatrixXd thresh_mm, const Eigen::VectorXi parcount, const int link, const int thresh_no_cov, const int negative, const int use_weights, const Eigen::VectorXd weights, const double out_val);
RcppExport SEXP _gotm_LLFunc(SEXP parametersSEXP, SEXP yiSEXP, SEXP reg_mmSEXP, SEXP thresh_mmSEXP, SEXP parcountSEXP, SEXP linkSEXP, SEXP thresh_no_covSEXP, SEXP negativeSEXP, SEXP use_weightsSEXP, SEXP weightsSEXP, SEXP out_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type reg_mm(reg_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_mm(thresh_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type parcount(parcountSEXP);
    Rcpp::traits::input_parameter< const int >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const int >::type thresh_no_cov(thresh_no_covSEXP);
    Rcpp::traits::input_parameter< const int >::type negative(negativeSEXP);
    Rcpp::traits::input_parameter< const int >::type use_weights(use_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type out_val(out_valSEXP);
    rcpp_result_gen = Rcpp::wrap(LLFunc(parameters, yi, reg_mm, thresh_mm, parcount, link, thresh_no_cov, negative, use_weights, weights, out_val));
    return rcpp_result_gen;
END_RCPP
}
// LLFuncIndv
Eigen::MatrixXd LLFuncIndv(const Eigen::Map<Eigen::VectorXd> parameters, const Eigen::VectorXi yi, const Eigen::MatrixXd reg_mm, const Eigen::MatrixXd thresh_mm, const Eigen::VectorXi parcount, const int link, const int thresh_no_cov, const int negative, const int use_weights, const Eigen::VectorXd weights);
RcppExport SEXP _gotm_LLFuncIndv(SEXP parametersSEXP, SEXP yiSEXP, SEXP reg_mmSEXP, SEXP thresh_mmSEXP, SEXP parcountSEXP, SEXP linkSEXP, SEXP thresh_no_covSEXP, SEXP negativeSEXP, SEXP use_weightsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type reg_mm(reg_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_mm(thresh_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type parcount(parcountSEXP);
    Rcpp::traits::input_parameter< const int >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const int >::type thresh_no_cov(thresh_no_covSEXP);
    Rcpp::traits::input_parameter< const int >::type negative(negativeSEXP);
    Rcpp::traits::input_parameter< const int >::type use_weights(use_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(LLFuncIndv(parameters, yi, reg_mm, thresh_mm, parcount, link, thresh_no_cov, negative, use_weights, weights));
    return rcpp_result_gen;
END_RCPP
}
// LLGradFunc
Eigen::MatrixXd LLGradFunc(const Eigen::Map<Eigen::VectorXd> parameters, const Eigen::VectorXi yi, const Eigen::MatrixXd YYY1, const Eigen::MatrixXd YYY2, const Eigen::MatrixXd reg_mm, const Eigen::MatrixXd thresh_mm, const Eigen::MatrixXd thresh_extd, const Eigen::VectorXi parcount, const int link, const int thresh_no_cov, const int negative, const int use_weights, const Eigen::VectorXd weights);
RcppExport SEXP _gotm_LLGradFunc(SEXP parametersSEXP, SEXP yiSEXP, SEXP YYY1SEXP, SEXP YYY2SEXP, SEXP reg_mmSEXP, SEXP thresh_mmSEXP, SEXP thresh_extdSEXP, SEXP parcountSEXP, SEXP linkSEXP, SEXP thresh_no_covSEXP, SEXP negativeSEXP, SEXP use_weightsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type YYY1(YYY1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type YYY2(YYY2SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type reg_mm(reg_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_mm(thresh_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_extd(thresh_extdSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type parcount(parcountSEXP);
    Rcpp::traits::input_parameter< const int >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const int >::type thresh_no_cov(thresh_no_covSEXP);
    Rcpp::traits::input_parameter< const int >::type negative(negativeSEXP);
    Rcpp::traits::input_parameter< const int >::type use_weights(use_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(LLGradFunc(parameters, yi, YYY1, YYY2, reg_mm, thresh_mm, thresh_extd, parcount, link, thresh_no_cov, negative, use_weights, weights));
    return rcpp_result_gen;
END_RCPP
}
// LLGradFuncIndv
Eigen::MatrixXd LLGradFuncIndv(const Eigen::Map<Eigen::VectorXd> parameters, const Eigen::VectorXi yi, const Eigen::MatrixXd YYY1, const Eigen::MatrixXd YYY2, const Eigen::MatrixXd reg_mm, const Eigen::MatrixXd thresh_mm, const Eigen::MatrixXd thresh_extd, const Eigen::VectorXi parcount, const int link, const int thresh_no_cov, const int negative, const int use_weights, const Eigen::VectorXd weights);
RcppExport SEXP _gotm_LLGradFuncIndv(SEXP parametersSEXP, SEXP yiSEXP, SEXP YYY1SEXP, SEXP YYY2SEXP, SEXP reg_mmSEXP, SEXP thresh_mmSEXP, SEXP thresh_extdSEXP, SEXP parcountSEXP, SEXP linkSEXP, SEXP thresh_no_covSEXP, SEXP negativeSEXP, SEXP use_weightsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type YYY1(YYY1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type YYY2(YYY2SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type reg_mm(reg_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_mm(thresh_mmSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type thresh_extd(thresh_extdSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi >::type parcount(parcountSEXP);
    Rcpp::traits::input_parameter< const int >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const int >::type thresh_no_cov(thresh_no_covSEXP);
    Rcpp::traits::input_parameter< const int >::type negative(negativeSEXP);
    Rcpp::traits::input_parameter< const int >::type use_weights(use_weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(LLGradFuncIndv(parameters, yi, YYY1, YYY2, reg_mm, thresh_mm, thresh_extd, parcount, link, thresh_no_cov, negative, use_weights, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gotm_dstdnorm", (DL_FUNC) &_gotm_dstdnorm, 1},
    {"_gotm_pstdlogit", (DL_FUNC) &_gotm_pstdlogit, 1},
    {"_gotm_dstdlogit", (DL_FUNC) &_gotm_dstdlogit, 1},
    {"_gotm_colpath", (DL_FUNC) &_gotm_colpath, 3},
    {"_gotm_extract_elements", (DL_FUNC) &_gotm_extract_elements, 3},
    {"_gotm_vglm2gotm_jurges_exp", (DL_FUNC) &_gotm_vglm2gotm_jurges_exp, 3},
    {"_gotm_ind_reg_thresh", (DL_FUNC) &_gotm_ind_reg_thresh, 3},
    {"_gotm_getThresholds", (DL_FUNC) &_gotm_getThresholds, 4},
    {"_gotm_LLFunc", (DL_FUNC) &_gotm_LLFunc, 11},
    {"_gotm_LLFuncIndv", (DL_FUNC) &_gotm_LLFuncIndv, 10},
    {"_gotm_LLGradFunc", (DL_FUNC) &_gotm_LLGradFunc, 13},
    {"_gotm_LLGradFuncIndv", (DL_FUNC) &_gotm_LLGradFuncIndv, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_gotm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
