#' @noRd
#' @keywords internal
hopit_msg <- function(x)
  switch(x,
         '1'  = 'Missing "$parcount" in model object.',
         '2'  = 'Missing model coefficients.',
         '3'  = 'Wrong number of parameters.',
         '4'  = 'Lambda must be given.',
         '5'  = 'Improving fit using nlm() method...',
         '6'  = 'Optimization cannot continue.',
         '7'  = 'Something is wrong with the survey package.',
         '8'  = 'Please specify the method of fit',
         '9'  = 'Unknown fit method.',
         '10' = 'Calculating starting parameters...',
         '11' = 'Fitting the model...',
         '12' = 'Calculating maximum latent range...',
         '13' = ' done\n',
         '14' = 'Calculating Hessian matrix...',
         '15' = 'Calculating LL gradient (estfun)...',
         '16' = 'Including survey design...',
         '17' = 'Unknown link function:',
         '18' = '\nThreshold variable(s) detected in reg.formula. Model may be not identifiable.\n', #start.vglm
         '19' = 'Starting set of parameters cannot be found using glm method.', #start.glm
         '20' = 'Wrong start method.', #get.hopit.start  UNUSED
         '21' = 'Threshold-Health variables must be factors.', #get.hopit.start
         '22' = 'boot must be of class "hopit.boot".', #boot
         '23' = 'No vcov detected.', #boot
         '24' = 'Are the levels', #checks
         '25' = 'sorted in incresing order?', #checks
         '26' = 'if not please set decreasing.levels to TRUE.', #checks
         '27' = '"decreasing.levels" must be given.', #checks
         '28' = 'Unknown method.', #checks
         '29' = 'The threshold formula should be given without dependent variable.', #checks
         '30' = 'The strata formula should be given without dependent variable.', #checks
         '31' = 'Offset not supported.', #checks
         '32' = 'Model is probably unidentifiable, $vcov (variance-covariance matrix) cannot be computed.', #checks
         '33' = 'Response must be a factor with ordered levels.', #checks
         '34' = 'Response must have 3 or more levels.', #checks
         '35' = 'Multiple weights specification detected. Please use either design or weights parameter.', #checks
         '36' = 'Vector of survey weights must be of the same length as data.', #checks
         '37' = 'Cannot compute variance-covariance matrix:\n', #generics
         '38' = 'Hessian cannot be calculated.', #generics
         '39' = '"robust.vcov" ignored, survey design was detected.', #generics
         '40' = 'Variance-covariance matrix:\n', #generics
         '41' = '\nVariance-covariance matrix adjusted for survey design.\n', #generics
         '42' = '\nVariance-covariance matrix based on sandwich estimator.\n', #generics
         '43' = 'Negative variaces detected, try different robust.se/survey options and check the fit!', #generics
         '44' = 'Survey weights detected. Standard errors were adjusted for survey design.\n', #generics
         '45' = 'Problem with some standard errors, please try option "robust.se" == TRUE.', #generics
         '46' = 'Something wrong.', #generics
         '47' = 'AIC for models with survey design not implemented yet.', #generics
         '48' = 'At least two objects must be listed.', #generics
         '49' = 'Anova (LRTs):\nMethod: "', #generics
         '50' = 'Unknown direction.', #generics
         '51' = 'Models have different survey designs.', #generics
         '52' = 'The "full" model must have more parameters than the "nested" one.', #generics
         '53' = 'Negligible differences between log likelihoods.', #generics
         '54' = 'The "nested" model has the higher likelihood than the "full" model. Try to improve the fit of the models.', #generics
         '55' = 'Theta parameter present in the nested model, but absent in full model.', #generics
         '56' = 'Probably non nested latent formulas (check reg.formula)).', #generics
         '57' = 'Probably non nested threshold formulas (check thresh.formula)).', #generics
         '58' = 'LRT for models with survey design not implemented yet.', #generics
         '59' = '\nLikelihood ratio test:\n', #generics
         '60' = 'Log likelihood maximum not reached.', #generics
         '61' = 'Problem in:', #generics
         '62' = 'All parameters seem to be at arg.max (at optimum).\n', #generics
         '63' = 'Scale factors', #generics
         '64' = 'Full model:\n', #generics
         '65' = "Formula (latent variables):", #generics
         '66' = "Formula (threshold variables):", #generics
         '67' = '\nNested model:\n', #generics
         '68' = 'Latent formulas are not nested.', #generics
         '69' = 'Threshold formulas are not nested.', #generics
         '70' = "Theta:", #generics
         '71' = '\nRobust SE were used (sandwich estimator of varcov).\n', #generics
         '72' = 'Link:', #generics
         '73' = 'Number of cases:', #generics
         '74' = 'Response levels:', #generics
         '75' = 'Log-likelihood:', #generics
         '76' = 'Deviance:', #generics
         '77' = 'Dispersion parameter (Theta):', #generics
         '78' = '\nCoefficients of the latent variable:\n', #generics
         '79' = '\nThreshold coefficients (Lambda):\n', #generics
         '80' = '\nThreshold coefficients (Gamma):\n', #generics
         '81' = '\nFixed Theta:\n', #generics
         '82' = '\nTheta:\n', #generics
         '83' = 'Unknown response.', #reporting styles
         '84' = 'Unknown group.labels.type.', #reporting styles
         '85' = 'Some cut-points are NA or duplicated.', #reporting styles
         '86' = '"formula" must be of class formula.', #reporting styles
         '87' = 'Elements of interaction(s)', #hopit
         '88' = 'should be present both in threshold and latent formula.',
         '89' = 'Latent variables present in threshold formula (or vice versa).',
         '90' = 'Non-interaction terms removed from crossinter.formula.'
  )
